// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWz4x3bUzryuZqT9n1qOWo8d0zH57zCI',
    appId: '1:920158121219:web:9b6ed5abcbf92757ec8d36',
    messagingSenderId: '920158121219',
    projectId: 'hobbyhobby-67c40',
    authDomain: 'hobbyhobby-67c40.firebaseapp.com',
    databaseURL: 'https://hobbyhobby-67c40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hobbyhobby-67c40.appspot.com',
    measurementId: 'G-YB8SLWDKD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZwFtvz6nyRPcVw9-0h8QkM8bT987HdtY',
    appId: '1:920158121219:android:5f922fc5a9364f75ec8d36',
    messagingSenderId: '920158121219',
    projectId: 'hobbyhobby-67c40',
    databaseURL: 'https://hobbyhobby-67c40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hobbyhobby-67c40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoHv-JFv8Xm0iqu5tT5yteIGv4xDS9RiI',
    appId: '1:920158121219:ios:0ae45096d874a08fec8d36',
    messagingSenderId: '920158121219',
    projectId: 'hobbyhobby-67c40',
    databaseURL: 'https://hobbyhobby-67c40-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hobbyhobby-67c40.appspot.com',
    iosClientId: '920158121219-qckaen7vounh0utdn08l0rataiil7d40.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbyhobby',
  );
}
